### ISSUE TITLE
[FEAT] 고교생 마이페이지 조회 api

### ISSUE THREAD

**Issue by biiit4894** [Team-SGBInside/SGBInside-Server#18]
## 📌  Feature Issue

- 고등학생 유저의 마이페이지 조회 api를 구현합니다. 

## 📝  To-do

- [x] 고교생 마이페이지 조회 api 구현
  - [x]  유저정보 조회
  - [x] 전체 활동 조회
  - [x] 활동 개별 조회 / 수정 / 삭제
