### ISSUE TITLE
[ADD] DB 연결

### ISSUE THREAD

**Issue by biiit4894** [Team-SGBInside/SGBInside-Server#2]
## 📌  Feature Issue
- RDS db를 연결합니다

## 📝  To-do

- [x] RDS db instance 생성
- [x] dataGrip db rds 연결
- [x] dataGrip db 테이블 생성
  - [x] 회원
  - [x] 창의적 체험활동
  - [x] 세부능력 및 특기사항
  - [x] 수상경력
  - [x] 독서활동상황
