### ISSUE TITLE
[FEAT] 고교생 창의적 체험활동 기록 api 구현

### ISSUE THREAD

**Issue by biiit4894** [Team-SGBInside/SGBInside-Server#5]
## 📌  Feature Issue

- 고등학생 회원의 창의적 체험활동 기록 api를 구현합니다
- pr 새로 만들어서 시작하기

## 📝  To-do

- [x] 고교생 창의적 체험활동 기록 api 구현
- [x] Cannot read properties of undefined 에러 해결
- [x] req.user 불러올 수 없는 점 해결
